spring:
  cloud:
    openfeign:
      client:
        config:
          # 默认配置
          default:
            logger-level: full
            connect-timeout: 3000
            read-timeout: 3000
          # 具体 feign 客户端的超时配置
          service-product:
            logger-level: full
            # 连接超时，3000 毫秒
            connect-timeout: 3000
            # 读取超时，5000 毫秒
            read-timeout: 3000
#            retryer:  feign.Retryer.NEVER_RETRY
    sentinel:
      transport:
        dashboard: localhost:8080
      # 懒加载/提前加载
      eager: true
      # true 统一web上下文 false 关闭上下文统一 例如 链路模式限流
      web-context-unify: false

#  Feign Sentinel 配置 熔断 开启之后 能使用默认fallback
feign:
  sentinel:
    enabled: true
