server:
  port: 9000

spring:
  profiles:
    # 这里配置的是命名空间
    active: public
    include: feign
  application:
    name: service-product
  datasource:
    url: jdbc:mysql://192.168.10.13:26316/seata_product?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: Password2017
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        # 默认使用dev
        namespace: ${spring.profiles.active:public}
        import-check:
          enabled: false
---
spring:
  config:
    import:
      - nacos:service-order.properties?group=order
      - nacos:service-product.properties?group=product
    activate:
      # 这里配置的是命名空间
      on-profile: public
---
spring:
  config:
    import:
      - nacos:service-order.properties?group=dev
      - nacos:service-product.properties?group=product
    activate:
      # 这里配置的是命名空间
      on-profile: dev
